name: usergrocery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 3.0.0
  cloud_firestore: 2.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: any
  firebase_core: 1.2.1
  firebase_storage: 8.1.1
  flutter_form_builder: any
  flutter_rating_bar: 4.0.0
  flutter_signin_button: any
  fluttertoast: any
  get: 4.1.4
  get_storage: any
  google_sign_in: any
  paginate_firestore: 1.0.0
  progress_indicators: 1.0.0
  sms_autofill: any
  upi_india: 3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
